permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author:
name: Ealing
email: yilongxie@qq.com
link: http://mbyte.cc
weibo:
github: http://github.com/linglong117
music:
linkedin:

# 站点信息
title: Move Bytes
description: My personal blog
url: http://mbyte.cc
rss_url: /pages/atom.xml

Source: /Users/yilongxie/mbytes
Destination: /Users/yilongxie/mbytes/_site
Incremental build: disabled. Enable with --incremental

Auto-regeneration: enabled for '/Users/yilongxie/mbytes'
Configuration file: /Users/yilongxie/mbytes/_config.yml
Server address: http://127.0.0.1:4000/

gems: [jekyll-paginate]


# gavatar头像及Favicon
gavatar: /public/img/gingko.jpg
favicon: /public/img/gingko.jpg

# google analytics 设置
ga:
id: UA-54262064-1
url: painterlin.com

# disqus 设置
disqus:
shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates:
- Optimization
- LaTeX

# 中文本地化
locals:
tags: 标签
about: 关于
newest: 最新文章
archive: 归档
